# Generated by Django 3.2.7 on 2022-07-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.TextField(max_length=100),
        ),
    ]
